### ISSUE TITLE
Can you provide a example script to can start making menus?

### ISSUE THREAD

**Issue by ElHave247** [LJW-Dev/Black-Ops-3-GSC-Compiler#1]
Hi i have using your work in xbox360 and i can load a jiggy menu v4.2 ported by craftycritter (I tryed myself to port Jiggy menu but didnt work, thinking if i can port i can start coding from that), but there is no source code or any example to understand how is the structure of gsc to make new scripts, if you can provide any base example, or a decompiler, or maybe if you have that source code helps me to understand how start making new scripts. Im not an expert but i have the game functions decompiled also so much dvars testing and recording everyone is works to later can use on scripts. Ill be so greatefull if you can help on that, i want to make some mods true for this game, like get zombie allies bots, also i have pc script code of zm bots to can translate to the console. Everything i try to port gives me error linking script scripts/mp/_destructilble.gsc and with the craftycritter port dont happen.

**Comment by ElHave247** [comment]
Obvious a waste of time...

**Comment by LJW-Dev** [comment]
It's been a while since i've gotten that error, but from what i remember that error occurs when one of the includes isn't available. Try loading a super small script initially and add more features over time, that's how I debugged my scripts. The source code of my ported jiggy menu was in the original download link if you want to look through it.

**Comment by ElHave247** [comment]
> It's been a while since i've gotten that error, but from what i remember that error occurs when one of the includes isn't available. Try loading a super small script initially and add more features over time, that's how I debugged my scripts. The source code of my ported jiggy menu was in the original download link if you want to look through it.

Can you link to that please? i didnt found the souirce downlaod you mean or wasnt available when i download the rest.

**Comment by LJW-Dev** [comment]
Here's the download link, the info folder has the source code: https://mega.nz/file/UNcH3TZK#vx0CmbldRCe5XNwyL-_sPYz2H3sqMLXTI74Nnt-3Bfc

**Comment by ElHave247** [comment]
> Here's the download link, the info folder has the source code: https://mega.nz/file/UNcH3TZK#vx0CmbldRCe5XNwyL-_sPYz2H3sqMLXTI74Nnt-3Bfc

Thanks so much im so greatefull
